"""OpenCode Agentで共有するBash権限方針。"""

from __future__ import annotations


DANGEROUS_BASH_PATTERNS = (
    "rm *",
    "sudo *",
    "doas *",
    "dd *",
    "mkfs*",
    "shred *",
    "truncate *",
    "wipefs *",
    "fdisk *",
    "parted *",
    "shutdown*",
    "reboot*",
    "poweroff*",
    "halt*",
    "systemctl poweroff*",
    "systemctl reboot*",
    "systemctl halt*",
    "git reset --hard*",
    "git clean *",
    "git checkout -- *",
    "git restore *",
    "git push*",
    "git -C * push*",
    "git branch -D*",
    "git worktree remove*",
    "git worktree prune*",
    "pnpm deploy*",
    "pnpm run deploy*",
    "pnpm publish*",
    "pnpm login*",
    "pnpm logout*",
    "pnpm changeset publish*",
    "pnpm exec changeset publish*",
    "pnpm release:*",
    "pnpm run release:*",
    "pnpm migrate:apply*",
    "pnpm exec wrangler deploy*",
    "pnpm exec wrangler d1 migrations apply*",
    "npx wrangler deploy*",
    "wrangler deploy*",
    "wrangler d1 migrations apply*",
    "pnpm exec wrangler *delete*",
    "npx wrangler *delete*",
    "wrangler *delete*",
    "pnpm exec wrangler secret *",
    "npx wrangler secret *",
    "wrangler secret *",
    "npm publish*",
    "npm login*",
    "npm logout*",
    "yarn npm publish*",
    "bun publish*",
    "docker push*",
    "docker login*",
    "docker logout*",
    "docker volume rm*",
    "docker system prune*",
    "docker compose * down *-v*",
    "terraform apply*",
    "terraform destroy*",
    "kubectl apply*",
    "kubectl delete*",
    "gh pr create*",
    "gh pr merge*",
    "gh pr close*",
    "gh pr edit*",
    "gh issue create*",
    "gh issue close*",
    "gh issue edit*",
    "gh repo create*",
    "gh repo fork*",
    "gh release create*",
    "gh release delete*",
    "gh release edit*",
    "gh release upload*",
    "gh repo delete*",
    "gh workflow run*",
    "gh auth login*",
    "gh auth logout*",
    "gh auth refresh*",
    "gh auth setup-git*",
    "gh auth switch*",
    "gh secret *",
    "gh variable *",
    "gh api *--method POST*",
    "gh api *--method PATCH*",
    "gh api *--method PUT*",
    "gh api *--method DELETE*",
    "gh api *-X POST*",
    "gh api *-X PATCH*",
    "gh api *-X PUT*",
    "gh api *-X DELETE*",
    "wrangler login*",
    "wrangler logout*",
    "pnpm exec wrangler login*",
    "pnpm exec wrangler logout*",
    "npx wrangler login*",
    "npx wrangler logout*",
    "agent-browser auth *",
    "agent-browser --profile *",
    "agent-browser --restore*",
    "agent-browser --state *",
)

SAFE_DEVELOPMENT_PREFIXES = (
    "pnpm format",
    "pnpm run format",
    "pnpm exec prettier",
    "pnpm exec eslint",
    "pnpm lint",
    "pnpm test",
    "pnpm build",
    "pnpm gen",
    "pnpm check",
    "pnpm add",
    "pnpm install",
    "pnpm update",
    "pnpm remove",
    "npm install",
    "npm update",
    "npm uninstall",
    "go test",
    "go vet",
    "mkdir",
    "git status",
    "git diff",
    "git log",
    "git show",
    "git grep",
    "git add",
    "git commit",
    "git merge",
    "git rebase",
)


def default_bash_permission() -> dict[str, str]:
    """通常の開発操作を許可し、実害のある操作だけを拒否する。"""

    return {"*": "allow"} | {
        pattern: "deny" for pattern in DANGEROUS_BASH_PATTERNS
    }
