receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_headers:
            - '*'
          allowed_origins:
            - http://www.localhost:5173
            - http://app.localhost:5174
            - http://admin.localhost:5176
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_max_size: 11000
    send_batch_size: 10000
    timeout: 10s

  signozspanmetrics/delta:
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    dimensions:
      - name: service.namespace
        default: default
      - name: deployment.environment
        default: default
      - name: signoz.collector.id
      - name: service.version
      - name: browser.platform
      - name: browser.mobile
      - name: host.name
      - name: host.type
      - name: container.name
    dimensions_cache_size: 100000
    enable_exp_histogram: true
    latency_histogram_buckets:
      - 100us
      - 1ms
      - 2ms
      - 6ms
      - 10ms
      - 50ms
      - 100ms
      - 250ms
      - 500ms
      - 1000ms
      - 1400ms
      - 2000ms
      - 5s
      - 10s
      - 20s
      - 40s
      - 60s
    metrics_exporter: clickhousemetricswrite
    metrics_flush_interval: 60s

exporters:
  clickhouselogsexporter:
    dsn: tcp://clickhouse:9000/signoz_logs
    timeout: 10s
    use_new_schema: true

  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000/signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true

  clickhousemetricswritev2:
    dsn: tcp://clickhouse:9000/signoz_metrics

  clickhousetraces:
    datasource: tcp://clickhouse:9000/signoz_traces
    low_cardinal_exception_grouping: ${env:LOW_CARDINAL_EXCEPTION_GROUPING}
    use_new_schema: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions:
    - health_check
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - clickhouselogsexporter
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - clickhousemetricswrite
        - clickhousemetricswritev2
    traces:
      receivers:
        - otlp
      processors:
        - signozspanmetrics/delta
        - batch
      exporters:
        - clickhousetraces
  telemetry:
    logs:
      encoding: json
    metrics:
      address: 0.0.0.0:8888
