emit:
  - '@typespec/openapi3'

output-dir: '{project-root}/tsp-output'

options:
  '@typespec/openapi3':
    emitter-output-dir: '{project-root}/openapi'
    output-file: 'openapi.json'
    file-type: 'json'
