name = "cfreact-template-frontend-app"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-11-13"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
